### ISSUE TITLE
zhongwen Chinese English dictionary : the C command does not work anymore?

### ISSUE THREAD

**Issue by Helendao** [cschiller/zhongwen#120]
Hi ,
I have been using the C command to copy (and paste) flawlessly so far until a couple days.
But now when I type "C" to copy the word pop up, it stills acknowledges "copied to clipboard", but when I paste, it doesn't work.
I don't get the content of pop up, but only the word that I highlighted.
I have already 
- desinstalled and reinstalled the dictionnary
- reset the options
- switched on /off computer
- my chrome version is the latest
Kindly advise. I am using this dictionnary every single day and it's so useful.. I am desperate to find a solution..
Thank you

**Comment by cschiller** [comment]
Thanks for your feedback, I'll take a look at this.

**Comment by cschiller** [comment]
I found the problem. It will be fixed later this week.

**Comment by Helendao** [comment]
GREAT! Thank you so much, I’m so happy to hear that !!Best, Sent from my iPhoneOn Jul 31, 2024, at 20:54, Christian Schiller ***@***.***> wrote:﻿
I found the problem. It will be fixed later this week.

**Comment by cschiller** [comment]
I fixed it. Version 6.1.0 is live. Your browser should update the extension automatically.

**Comment by Helendao** [comment]
Yes it works again!!:)
Thanks a lot for dealing with this promptly. I am SO relieved :))

**Comment by cschiller** [comment]
Great! :)

Alternatively, you can also use the built-in word list for saving entries (press "R" in instead of "C", it will add the word to the list, then use "Alt + W" to show the list). In the list you can select the rows you want to save and then click on "Save selected rows" to save them to a text file. Each row in this file has the same format as the one you get by copying the entry via the "C" keyboard shortcut.

**Comment by Helendao** [comment]
Thank you for sharing, well noted Will try this as well !Have a nice weekend ☺️Sent from my iPhoneOn Aug 3, 2024, at 09:57, Christian Schiller ***@***.***> wrote:﻿
Great! :)
Alternatively, you can also use the built-in word list for saving entries (press "R" in instead of "C", it will add the word to the list, then use "Alt + W" to show the list). In the list you can select the rows you want to save and then click on "Save selected rows" to save them to a text file. Each row in this file has the same format as the one you get by copying the entry via the "C" keyboard shortcut.
