### ISSUE TITLE
Zhongwen not working in Firefox

### ISSUE THREAD

**Issue by wscholine** [cschiller/zhongwen#121]
What the title says. I noticed a couple of weeks ago that it had stopped working.

I confirmed that Zhongwen on Chrome was working with sites where it was not working with Firefox.

**Comment by cschiller** [comment]
Do you have any specific sites it's not working on? Have you activated the extension by clicking on its icon? (The red "on" banner should be displayed.)

**Comment by wscholine** [comment]
OK, somehow I had gotten it turned off.

I did have to edit the settings to display the icon for the extension to
turn it back on, which surprisingly is apparently a different setting than
the enable/disable in extensions manager.

You can close this one as due to pilot error.

**Comment by cschiller** [comment]
No problem, I'm glad it works for you again.
