### ISSUE TITLE
Keyboard shortcuts can be activated without popup

### ISSUE THREAD

**Issue by Hirse** [cschiller/zhongwen#16]
1. The <kbd>R</kbd> key add the last opened word(s) to the Word List even when the popup is 
not open.
  ![B1A5A2FE-E104-4D4E-A475-1B67ED195304](https://user-images.githubusercontent.com/2564094/60682315-b222c300-9e47-11e9-8a35-f858df7646af.GIF)
2. The <kbd>Alt</kbd> + number shortcuts work on any selected text. (Even when the popup is open on something else.)
  ![292E43A6-733B-44B5-B8B7-B816C987095D](https://user-images.githubusercontent.com/2564094/60682336-c8c91a00-9e47-11e9-8479-5aac6cac93c6.GIF)

I am not sure if either are intentional, but imho it would make more sense to only allow shortcuts when the popup is opened.

**Comment by cschiller** [comment]
It's not intentional. I'm not sure anybody has run into this problem before. It ought to be fixed, though.

**Comment by Hirse** [comment]
I can give it a try later, just wanted to check with you before I spend any time.

**Comment by cschiller** [comment]
Sure. I'd say it's not super urgent, but it's a nice catch. :)

**Comment by cschiller** [comment]
I commited a bugfix.

**Comment by cschiller** [comment]
Fixed in version 5.5.0
