### ISSUE TITLE
Pop-up Definitions Don't Show Phrases 

### ISSUE THREAD

**Issue by amaryllisraine** [cschiller/zhongwen#23]
I noticed recently that the pop-up doesn't sense phrases/multiple words anymore on Google Docs. I tried this with known phrases that have been defined using the extension before and the pop-up only defines each word one by one.

**Comment by Qwertx23** [comment]
I am also having the same problem. It started yesterday. Are there any solutions? Thank you.

**Comment by cschiller** [comment]
There weren't any changes to Zhongwen since the latest release on July 8. Maybe Google broke it by changing the HTML on Google Docs somehow. Right now I don't have a workaround for this.

**Comment by cschiller** [comment]
@amaryllisraine @Qwertx23 : I cannot confirm this problem. It seems to work just fine. Can you verify that this is still an issue for you?

**Comment by Qwertx23** [comment]
Hi, this is still an issue for me. It shows one word by one word in google docs but worked fine elsewhere.

**Comment by cschiller** [comment]
@Qwertx23 , I'm pretty sure there's something unusual about your document, because, as you said, Zhongwen otherwise works fine for you. Is there a space after every character, or something like that? Because that would lead to this kind of behavior.

**Comment by Qwertx23** [comment]
Nope. I downloaded it in firefox and it is working fine. Somehow i think is google doc in chrom. 


Sent from Yahoo Mail for iPhone


On Sunday, August 11, 2019, 19:45, Christian Schiller <notifications@github.com> wrote:


@Qwertx23 , I'm pretty sure there's something unusual about your document, because, as you said, Zhongwen otherwise works fine for you. Is there a space after every character, or something like that? Because that would lead to this kind of behavior.

**Comment by cschiller** [comment]
@Qwertx23 : Maybe you have another Chrome extension installed that's somehow interfering with Zhongwen on Google Docs? You could test this by temporarily disabling all other extensions on the extensions page, then restarting the browser and then checking whether the problem with Google Docs persists.

**Comment by sushirollu** [comment]
Hello, sorry to jump in the thread but I am also experiencing this issue in Google Docs on Chrome. I do not believe it is an extension interfering as I have not installed any new extensions and only have two currently (this and an adblocker), nor is it an issue with my document formatting, as I tested it on a document that Zhongwen used to work on and that I have not edited in any way since, and the problem persists. In addition, I copy-pasted a section of text from elsewhere into a Google Doc, and found that Zhongwen will recognise the phrase on the original website, then fail to do the same on the Google Doc.

**Comment by cschiller** [comment]
@sushirollu : Just to clarify, you're using the Chrome version of Zhongwen, not the Forefox one, right?

**Comment by sushirollu** [comment]
Yes, that is correct.

**Comment by cschiller** [comment]
@sushirollu : When you type in the same text instead of pasting it, is the Zhongwen behavior the same? I still haven't been able to reproduce this problem.

**Comment by sushirollu** [comment]
Yes, it does. If I may ask, is your Chrome Version 76.0.3809.100 (Official Build) (64-bit)? The only thing I can think of that is different from when Zhongwen worked and now that it does not is potentially updating my Chrome, as it updates whenever it closes.

**Comment by cschiller** [comment]
@sushirollu Yes, the Chrome version is the same. I don't think your ad-blocking extension is causing it, but could you test it once more with only the Zhongwen extension enabled? I just want to make sure we can rule out that another extension is causing it.

**Comment by sushirollu** [comment]
I have done so and unfortunately the problem persists.

**Comment by cschiller** [comment]
And you're using Windows 10, right?

**Comment by cschiller** [comment]
![GDScreenshot](https://user-images.githubusercontent.com/10326440/62859550-116dd000-bd30-11e9-872c-562a9114d172.PNG)

**Comment by sushirollu** [comment]
Oh, no, I am on 8.1.

**Comment by cschiller** [comment]
It works for me. (see screenshot above)

Have you made any changes to your default settings that might be causing it?

**Comment by cschiller** [comment]
I think the Windows version shouldn't matter. I just wanted to know whether you're using Windows, macOS or Linux.

**Comment by sushirollu** [comment]
I do have some changes from the default settings but these settings predate the change in Zhongwen behavior by several months. I am using Windows.

**Comment by cschiller** [comment]
So at this point I believe Google made some changes to Google Docs recently. For some users these changes are causing the behavior you are observing. However, not all users seem to be affected.

**Comment by sushirollu** [comment]
![12](https://user-images.githubusercontent.com/54023510/62859973-63632580-bd31-11e9-93e3-cb52bf729470.PNG)

**Comment by sushirollu** [comment]
I'm not sure if it will help but I've sent an example of the change.

I see, thank you for your time.

**Comment by cschiller** [comment]
Thanks for your feedback. Maybe with the help of some other people who are also having this problem we can determine the cause and find a workaround.

**Comment by sushirollu** [comment]
Thank you for your work and I hope a solution can be found soon.

**Comment by amaryllisraine** [comment]
Hello, sorry I didn't reply earlier, but this is still an issue for me. However, as @Qwertx23 also pointed out, the weird issue is only happening when I use Google Docs on a Google Chrome Browser, while the add-on senses phrases fine when I use Google Docs on the Mozilla Firefox browser. This leads me to believe it's a browser issue, or perhaps changes were made to Google Docs in Chrome that did not affect Firefox. I've attached pictures:

![pasted image 0 (2)](https://user-images.githubusercontent.com/53952582/62873634-c6cb6400-bced-11e9-9bc2-ac5b48fe2c49.png)
![pasted image 0 (3)](https://user-images.githubusercontent.com/53952582/62873635-c763fa80-bced-11e9-927d-7b5a8b4d8c88.png)

**Comment by cschiller** [comment]
@amaryllisraine : What's really strange is that it works for me even in Chrome. There must be something else. Have you made any changes to the Google Docs default settings?

**Comment by Qwertx23** [comment]
I gave up in chrome and went to use it in firefox. 


Sent from Yahoo Mail for iPhone


On Tuesday, August 13, 2019, 15:08, Christian Schiller <notifications@github.com> wrote:


@amaryllisraine : What's really strange is that it works for me even in Chrome. There must be something else. Have you made any changes to the Google Docs default settings?

**Comment by amaryllisraine** [comment]
@cschiller Hmm, I'm pretty sure I didn't make any changes to the default settings and even if I did, since I'm still using Google Docs on both browsers with the same email account, so the settings would carry over right? This is really such a mystery haha! Thankfully it is still functional on Firefox which is a huge relief. I hope we'll get to the bottom of this eventually, but regardless, the extension is really an amazing help to me, and so thanks for developing it!

**Comment by Shifen-Betty-Wu** [comment]
The extension doesn't seem to be working in Google Docs for me either. It can't sense phrases, only single individual characters. I just started having this problem today and it was still working a few days ago. I reinstalled the extension and I still have the same problem. Please fix!!

**Comment by chendaddy** [comment]
Also jumping in to say I am experiencing the exact same issue, the plugin is no longer sensing phrases in Google Docs in Chrome 76.0.3809.100 (Official Build) (64-bit) on a Windows 10 PC. Still works on other sites, even Gmail. I haven't tested yet on my Macbook. Didn't realize there was a Firefox extension. I guess I'll just be using that for the time being, but I really hope a fix can be made for Chrome soon.

**Comment by chendaddy** [comment]
> Also jumping in to say I am experiencing the exact same issue, the plugin is no longer sensing phrases in Google Docs in Chrome 76.0.3809.100 (Official Build) (64-bit) on a Windows 10 PC. Still works on other sites, even Gmail. I haven't tested yet on my Macbook. Didn't realize there was a Firefox extension. I guess I'll just be using that for the time being, but I really hope a fix can be made for Chrome soon.

Confirmed also a problem for MacBook Air, running macOS Mojave 10.14.6 (18G87) using the same Chrome build.

**Comment by cschiller** [comment]
I can now reproduce this problem, too. Only Chrome is affected. It works in Firefox.

**Comment by singlemom484** [comment]
Would like to add that I have been affected by this too in Google Docs in Chrome. Sorry, I'm not sure how Github works, but I'm posting here so that I can be aware of updates when this is resolved, as I'm forced to use Firefox in the meantime.

**Comment by cschiller** [comment]
I just released a workaround for this issue in version 5.6.0.

The problem was caused by changes Google made to the Google Docs files, but apparently only to the ones loaded in Chrome, not the Firefox ones.

**Comment by chendaddy** [comment]
> I just released a workaround for this issue in version 5.6.0.
> 
> The problem was caused by changes Google made to the Google Docs files, but apparently only to the ones loaded in Chrome, not the Firefox ones.

Workaround works, thanks Christian!
