### ISSUE TITLE
Read pdf's

### ISSUE THREAD

**Issue by AdrianStobbe** [cschiller/zhongwen#24]
Hello, I really love your extension and saves a lot of time.
Unfortunately I didn't find a way to use your tool in pdfs opened in Chrome. The text can be copied (it's a text pdf), but still I cannot activate the addon within the document?

Is there a way to fix this?

I am really looking forward to an answer

Thanks!

**Comment by cschiller** [comment]
Hi @AdrianStobbe,

Unfortunately there's no way to fix this. For technical reasons Zhongwen only works with HTML files, not with PDF files.

**Comment by AdrianStobbe** [comment]
Hi @cschiller ,
I am thinking of writing an extension to read PDF files. Do you think that I could build on your software or would I probably need to rewrite a big part?

Thanks a lot

**Comment by cschiller** [comment]
You would need a complete rewrite. I don't know whether it would even be possible. I would recommend converting your PDF files to HTML and then using Zhongwen.
