### ISSUE TITLE
Keybaord shortcut for Firefox?

### ISSUE THREAD

**Issue by Thomasc5** [cschiller/zhongwen#25]
I can set a keyboard shortcut to enable/disable the zhongwen extension in Chrome. May I ask is there a way to do the same in Firefox? (e.g. in Firefox's "Manage Extension Shortcuts" menu)

Thank you!

**Comment by cschiller** [comment]
I'll add it in the next release.

**Comment by cschiller** [comment]
Fixed in version 5.7.0
