### ISSUE TITLE
 Pop-up window issue

### ISSUE THREAD

**Issue by Thomasc5** [cschiller/zhongwen#26]
On some Chinese websites, the texts in the pop-up window don't seem to display properly. For exmaple:

![1](https://user-images.githubusercontent.com/5540385/65566646-1a37ff80-df86-11e9-83fd-6c205e08715c.jpg)
[https://hk.on.cc/hk/bkn/cnt/amenews/20190925/bkn-20190925060138538-0925_00972_001.html](url)

**Comment by cschiller** [comment]
The problem on the page you mentioned is a CSS file that sets the line-height to 1.0em, which affects the layout of the pop-up window. Unfortunately, there's not much that can be done about this. The culprit here is not Zhongwen, but the layout definition of the page itself.
