### ISSUE TITLE
Text-To-Speech pronunciation?

### ISSUE THREAD

**Issue by Thomasc5** [cschiller/zhongwen#27]
I use an app called Pleco on iPhone with offline text-to-speech pronunciation. I was wondering if the same can be done on a Firefox/Chrome browser with an extension like zhongwen? (e.g. right click to hear the pronunciation of a character/vocabulary)

**Comment by cschiller** [comment]
Zhongwen uses Hanyu Pinyin and/or Zhuyin, a.k.a. Bopomofo, for showing the pronunciation. There are many good resources for learning Pinyin and Bopomofo, so I'm not planning to add text-to-speech pronunciation to Zhongwen.
