### ISSUE TITLE
(Android Firefox) enable/disable function

### ISSUE THREAD

**Issue by Thomasc5** [cschiller/zhongwen#29]
I'd like to replace the unofficial fork with yours but I noticed that the official one can't be enable/disable with a quick touch over the add-on in the kebab menu. 

Could you add a quick enable/disable function there for Android Firefox?  Many thanks!   

![Screenshot](https://user-images.githubusercontent.com/5540385/66448739-1ecfde00-ea85-11e9-9748-601dba2f63d8.jpg)

**Comment by cschiller** [comment]
I haven't tested Zhongwen in Firefox for Android yet. I guess most of the features that require keyboard interaction won't work. At least I'm not sure how you would make the keyboard visible when reading a web page. I'll take a look at it and see what I can do.

**Comment by cschiller** [comment]
Fixed in version 5.7.1.
