### ISSUE TITLE
Tone Colors

### ISSUE THREAD

**Issue by thomashirtz** [cschiller/zhongwen#3]
Hello,
Would it be possible to add an option to choose tone color; I learned all my Chinese with the "hanping tone colors". And it really bother me a lot the color used on your add-on.
https://resources.allsetlearning.com/chinese/pronunciation/Tone_colors
So my suggestion is to implement the most common combinations (or even better, be able to do custom color ?)
Otherwise, great job :)
Thanks

**Comment by cschiller** [comment]
Hi @thomashirtz , so as a workaround for now you can turn off tone colors on the options page.
I think what I might do is add an option for some widely used color schemes. I think making colors completely customizable is not necessary and might actually be somewhat confusing.
Can you send me the colors that Hanping is using?

**Comment by thomashirtz** [comment]
Hi, I agree for the color completely customizable; I did remove the color for now

I sent a link with the most common color :
https://resources.allsetlearning.com/chinese/pronunciation/Tone_colors

Name |1st Tone | 2nd Tone | 3rd Tone | 4th Tone | Neutral Tone
**Hanping | light blue | green | orange | red | gray**
Dummit | red | orange | green | light blue | (none)
Pleco | red | green | blue | purple | gray
Sinosplice | orange | green | blue | red | gray
MDBG | red | orange | green | blue | black

Thank you :)

**Comment by cschiller** [comment]
I added Pleco and Hanping for now, since they seem to be the most common alternatives. If needed, I can add the other color schemes later.

**Comment by thomashirtz** [comment]
Really nice!
