### ISSUE TITLE
Remember the popup position

### ISSUE THREAD

**Issue by alidouiyek** [cschiller/zhongwen#35]
Hi there ! 
On some websites, hovering a word triggers a popup from the website,  so I need to move the Zhongwen popup manually with X/Y . But when I hover on another word, the popup is back at its original position and I need to move it again.  
Btw I also have the same problem because I use some other extensions that have their own popup windows which hide the Zhongwen popup.
On the pic below you can see Zhongwen partially hiding the dropdown menu, and Zhongwen itself is hidden by another black popup (that's my other extension: Flewent).

Could you add an option to save the position of the popup ?

![Untitled1](https://user-images.githubusercontent.com/6524698/69483778-8475ff00-0e66-11ea-98d1-38c0cdf2f92f.png)

**Comment by cschiller** [comment]
When you type 'A' on your keyboard while the pop-up window is shown it cycles through three positions: upper-left corner, lower-right corner, and regular position. It also remembers this position when you hover over another word, either with the mouse or by using the keyboard. I think this should solve your problem.
