### ISSUE TITLE
Forvo Integration

### ISSUE THREAD

**Issue by Chrono7** [cschiller/zhongwen#38]
Would you consider adding Forvo integration? It's a great site for getting native pronunciations, and I assume would require little effort to implement - it could work like one of the dictionaries available by shortcut. Alternatively, you could allow users to customize the dictionaries/websites accessible by the shortcuts.

**Comment by cschiller** [comment]
I added this in the latest version (5.9.0). You can use the "Alt + 2" shortcut for it.
