### ISSUE TITLE
Need to click on the extension logo to make it works

### ISSUE THREAD

**Issue by thomashirtz** [cschiller/zhongwen#4]
Hello,
When I open my browser, the extension does not work right away (Even if the logo Zhongwen" indicate "on" in red). I need to click on the extension logo, only thereafter it starts displaying when I hover over text. (It seems like the extension is by default off when opening the browser even though the logo says it is on)
Best regards,

**Comment by cschiller** [comment]
Hi @thomashirtz , I tested it, but it works for me. Could you tell me the version of Chrome you're running? Also, are you using Windows, macOS or Linux? Thanks!

**Comment by thomashirtz** [comment]
Hi
Windows 10 Familial
Version 72.0.3626.119 (Build officiel) (64 bits)
You are welcome!

**Comment by cschiller** [comment]
Hi @thomashirtz , I just released version 5.2.0. This version should fix this issue.

**Comment by cschiller** [comment]
I made another little change, so try version 5.2.1 now and let me know if it works for you.

**Comment by thomashirtz** [comment]
It does work perfectly!
Nice job
