### ISSUE TITLE
Don't display "On" on the extension icon

### ISSUE THREAD

**Issue by himat** [cschiller/zhongwen#43]
It is incredibly distracting that the word "On" is in a bright red box on the extension bar.
Can you remove this?

**Comment by cschiller** [comment]
I'm sorry you find this "incredibly distracting". However, it does give important feedback to the user, namely whether the extension is active ("On") or inactive. The translations only appear when the extension is active. I would recommend turning off the extension when you're not using it (simply by clicking on its icon), then the "On" label will disappear.

**Comment by cschiller** [comment]
By the way, when you right-click on the extension icon, there's an option "Hide in Chrome Menu". This will remove the icon from the toolbar and move it to the Chrome menu to the right. If you want to leave the extension active the whole time I think this would be the easiest solution for your problem. Hope this helps!

**Comment by himat** [comment]
That's actually a really good suggestion that fixes it for me - thanks!!
