### ISSUE TITLE
Doesn't work on linux

### ISSUE THREAD

**Issue by dims12** [cschiller/zhongwen#46]
This is it. Nothing happens when hover on Chinese word. Sometimes selection is updating, but popup doesn't appear. Extension is active, no error messages appear.

**Comment by cschiller** [comment]
- What Chrome version are you using? Is it Chrome or Chromium?
- Did you activate the extension by clicking on its icon and does it say "On"? 
- Could you temporarily disable any other extensions you might have installed to see whether they somehow interfere with Zhongwen?
- In case you're using Zhongwen to read a local file, you first need to grant access to file URLs to make it work.
