### ISSUE TITLE
[Feature request] Add with R the only one translation to the word-list

### ISSUE THREAD

**Issue by Yunir** [cschiller/zhongwen#48]
When tapping to R it will add all the queries to the word list, but it would be good to add the only "phrase" word, but not the separate first character translations. 
Maybe it will be good to add arrows or other hotkeys to navigate and choose the best translation.

**Comment by cschiller** [comment]
There is an option for this already on the options page:

![Capture](https://user-images.githubusercontent.com/10326440/103378429-90f56e00-4ae2-11eb-8c06-bab5cce82ba2.PNG)
