### ISSUE TITLE
Make Available for Safari

### ISSUE THREAD

**Issue by gwilymjames** [cschiller/zhongwen#56]
I believe the latest version of Safari allows for simple conversion of Chrome extensions onto Safari. Zhongwen is my most used extension, and it would be great if you could look into it.

**Comment by cschiller** [comment]
I believe Apple charges $99 / year for the Apple Developer Program. I'm providing Zhongwen as a free extension, so I will not port it to Safari since I don't think you'd be willing to pay me $99 / year for it. 😉

I would suggest you keep using Chrome.
