### ISSUE TITLE
Feature to pop-up on demand

### ISSUE THREAD

**Issue by stump000** [cschiller/zhongwen#63]
Thank you for this great app.

It seems the only way to use is to manually activate/deactivate Zhongwen app, then all mouse-over text gets a popup. I was wondering if it would be possible to pop-up only when pressing a hotkey (e.g. by pressing SHIFT), so that Zhongwen can stay turned on most of the time but not distract with popups when not needed.

Just passing the idea! Sorry if it doesn't work this way as I am new to the GitHub!

**Comment by delozi** [comment]
Good idea. I think this should be added as well.

**Comment by cschiller** [comment]
Hi @stump000 and @delozi, you can already do this. Just go to chrome://extensions/shortcuts and configure the shortcut there.

**Comment by delozi** [comment]
> Hi @stump000 and @delozi, you can already do this. Just go to chrome://extensions/shortcuts and configure the shortcut there.

Thank you. I guess this is fine to close then.
