### ISSUE TITLE
Please add donation option, this extention is too good

### ISSUE THREAD

**Issue by maraoz** [cschiller/zhongwen#65]
I've been using this extension for 5 months already, and it's stable, easy to use, and very useful! I came to the github page looking to donate some $/crypto as a thank you gesture, and couldn't find how! :)

If you don't want donations, accept my huge thanks and virtual love ❤️ 
amazing work!!

**Comment by cschiller** [comment]
Hi @maraoz, Thank you so much for the nice feedback. I'm glad that you find Zhongwen useful. Of course, Zhongwen is, and will always remain, free. But if you do want to make a small donation, you can use this link: https://paypal.me/chris8765

Thanks again and keep enjoying Zhongwen!
