### ISSUE TITLE
Link to Skritter outdated

### ISSUE THREAD

**Issue by brookegeorge** [cschiller/zhongwen#74]
Hey guys! Just found this and very excited to share with my Chinese students. I have a skritter account for each student and would love to use the add to skritter function but it seem like you have an old link? 

Thanks!

**Comment by cschiller** [comment]
Hi @brookegeorge, actually the "add to Skritter" function works fine, it's just that the page you end up on when adding a word still uses the old Skritter design. Nonetheless, you can use the new Skritter UI (or Skritter on your phone or tablet) with the words you added through Zhongwen. It's completely unrelated to the design of the landing page from Zhongwen.
