### ISSUE TITLE
Request: Please list definitions in order of most common to least common

### ISSUE THREAD

**Issue by kongming819** [cschiller/zhongwen#79]
Very many times, something like this happens in the add-on:

![image](https://user-images.githubusercontent.com/5245944/126920293-858f1af5-f840-4a28-87d7-81a008ed36ba.png)

The most common use of the character is at the bottom, whereas the really esoteric, obscure definition is at the top. This is counter-productive for Chinese language learners, as people often gravitate towards the first listed definition.

**Comment by kongming819** [comment]
Another thing is that surnames are often listed first, along with the more esoteric definition
![image](https://user-images.githubusercontent.com/5245944/126921394-95a0d81f-eb3a-4bf0-a6ad-403302ca1329.png)

While listing surname first is not such a big deal, it can be confusing for some of the more common words, such as 从 and 加.
Such as: 
![image](https://user-images.githubusercontent.com/5245944/126921480-e61f25f8-63c8-4815-9d65-074489bc10ae.png)

Also this: 
![image](https://user-images.githubusercontent.com/5245944/126921522-a524afaa-9b03-4dd3-b4cf-87649c854e56.png)

This one has the correct order of definitions:
![image](https://user-images.githubusercontent.com/5245944/126921117-f8f4746f-07bb-472b-b921-99fcccd443d0.png)

On a semi-related note, there's another kind of order issue where something like this happens: 
![image](https://user-images.githubusercontent.com/5245944/126920920-4749fd5c-5c8a-47a8-9d9c-899eb7e2ef91.png)
Listing variants first, none of which are the character highlighted. Great to see when there is actually a variant in question, but very distracting and quite confusing when all I want is just the definition.

This one is correct:
![image](https://user-images.githubusercontent.com/5245944/126921010-25fe77c2-7b09-4e8b-96f4-9a632e62dd76.png)
(Why is this one correct but not the other?)

Then in other cases:
![image](https://user-images.githubusercontent.com/5245944/126920963-6bec5a5f-40cf-43b2-8fca-ebed212c8eb8.png)
Only lists the variant with no definition.

Here's an example that combines both:
![image](https://user-images.githubusercontent.com/5245944/126921228-0aaa979a-67b5-4565-b6e5-34dc824af603.png)
Not only does it give a variant that is not relevant, it also puts the definition on the bottom

**Comment by cschiller** [comment]
Zhongwen displays entries from the built-in CC-CEDICT dictionary. In its current form, CC-CEDICT does not provide the extra information that would be necessary for ranking the entries as you described. So unfortunately there's no way to tell how the entries should be reordered.
