### ISSUE TITLE
Feature request: Implement an option to show & highlight only when a modifier key is pressed

### ISSUE THREAD

**Issue by jhanschoo** [cschiller/zhongwen#8]
This feature is useful especially when I want to primarily perform e.g. copy/paste operations on a page and only occasionally look up definitions.

You can have a look at

https://github.com/melink14/rikaikun

that implements this feature gated by the `showOnKey` option.

**Comment by cschiller** [comment]
Hi @jhanschoo , could you give me a more detailed description of this feature request? What is the problem you're trying to solve and what does your proposed solution look like to the end user? Thanks!

**Comment by jhanschoo** [comment]
Current behavior:

When the mouse is over han characters, an appropriate term that includes the moused-over character is highlighted, and an appropriate popup gets displayed.

Proposed behavior:

A configuration setting should be made available, which can be set to one of the modifier keys (e.g. Ctrl, Alt, etc.), or left blank.

* If it is left blank, then behavior should be unchanged.
* Suppose that it is set to the Alt modifier key. Then whenever the mouse is over a Chinese character but the Alt key is not pressed, no popup must be displayed and the extension should not change what is currently highlighted on the page. On the other hand, if the mouse moves over a Chinese character while a modifier key is pressed, the extension exhibits identical behavior as the current behavior (highlighting terms and displaying a popup for them).
* There is the question of behavior when the modifier key is released while the popup is showing or when a modifier key is pressed while the mouse is over a Chinese character and the popup is not showing, but these side cases are arguably not very important if it is not feasible to handle them very cleanly.
* Likewise for other modifier keys, and if support is desired, modifier key combinations.

User story:

* John is practicing Chinese comprehension. John encounters a place name, for which Zhongwen does not give a definition for. He wants to Google for the name, and proceeds to highlight it with the mouse cursor. Without the feature, the extension interferes with John's attempt to highlight the multi-character term by instead highlighting single characters. With the feature, John is able to highlight the term without trouble and copy them to the clipboard. Then, when John wishes to use Zhongwen for a common term he does not understand, he holds down the Alt key, and Zhongwen would give popup definitions as usual.

Notes:

This feature has been implemented in the version of rikaikun for chrome that I have linked above, and with the configuration saved under the the name `showOnKey` in various places. Since zhongwen and that version of rikaikun share a common ancestor codebase, I thought that it would save work to investigate how it is implemented there.

Thanks for looking into it!

**Comment by cschiller** [comment]
Hi @jhanschoo ,

I think your problem can easily be solved by deactivating the extension whenever you want to select text for copying it to the clipboard. Afterwards you can activate it again.

When you go to chrome://extensions/shortcuts you can even define a keyboard shortcut for doing this, i.e. you could choose the "Alt + Z" shortcut for activating/deactivating Zhongwen.

**Comment by jhanschoo** [comment]
Ah that is feasible for me; the extension toggles reasonably fast. Implementing this may still be useful in terms of ease of workflow, so I'll leave it to you to choose to close the issue. Thanks!

**Comment by cschiller** [comment]
I think the main problem with your proposal is that it would interfere with the existing keyboard shortcuts, such as links to external dictionaries, Skritter and Tatoeba. Since there's another solution for your use case I'm going to close this feature request. Thanks for your feedback, though!
