### ISSUE TITLE
Extension Type?

### ISSUE THREAD

**Issue by Pacers31Colts18** [cschiller/zhongwen#9]
Hello,

We work in a controlled environment where by default we blacklist every Google Chrome extension, and then whitelist ones that our sec team has approved. I have this added to our whitelist, but can not install. My assumption is the app_type is off somehow.

Can you confirm what "type" of extension this is? https://www.chromium.org/administrators/policy-list-3#ExtensionAllowedTypes

"extension", "theme", "user_script", "hosted_app", "legacy_packaged_app", "platform_app".

Can you also confirm the extension ID is still kkmlkkjojmombglmlpbpapmhcaljjkde?

**Comment by cschiller** [comment]
Hi @Pacers31Colts18 , the extension ID is correct. I would assume the extension type is "extension". It is not set by the extension itself, though.
