### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by jamesmurdza** [cschiller/zhongwen#92]
I am aware that there used to be a version that worked on mobile Firefox but not anymore.

So I tried installing the zhongwen extension on Kiwi Browser which is a mobile Chromium-based browser which supports Chrome extensions. Not surprisingly, it installed but the pop-ups don't show.

Do you know if the extension has ever worked on mobile Chromium browsers or how much of an effort it would be to make it work?

Thanks!

**Comment by chinese-words-separator** [comment]
> I am aware that there used to be a version that worked on mobile Firefox but not anymore.
> 
> So I tried installing the zhongwen extension on Kiwi Browser which is a mobile Chromium-based browser which supports Chrome extensions. Not surprisingly, it installed but the pop-ups don't show.
> 
> Do you know if the extension has ever worked on mobile Chromium browsers or how much of an effort it would be to make it work?
> 
> Thanks!

Zhongwen is working on Kiwi Browser. Tap the ellipsis first, then tap Zhongwen's icon to activate it. Zhongwen not activated upon install

![image](https://user-images.githubusercontent.com/91402471/173827761-28f39c87-3590-40b4-8a0e-87e2a6a1495a.png)

**Comment by jamesmurdza** [comment]
Hi @chinese-words-separator, great that it is working on mobile! Must have been my mistake. Thanks.
